[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.2.1"
itertools = "0.12.0"
prime_factorization = "1.0.4"
rand = "0.8.5"
regex = "1.10.2"
